version: '3.8'
services:
  dev:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./oj:/oj
    working_dir: /app
    command: sleep infinity
    ports:
      - "20211:8080"